// Refreshes the generated hero data:
//   src/data/heroes.generated.ts          hero list from OpenDota (names, attributes, roles)
//   src/data/hero-abilities.generated.ts  every hero's current abilities + patch, from Valve's
//                                          official datafeed (it tracks lettered patches like 7.41f)
// Run after a new hero or patch is released, then add new heroes to src/data/hero-meta.ts
// (the test suite fails until you do, so it can't be forgotten).
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OPENDOTA = 'https://api.opendota.com/api/constants';
const VALVE = 'https://www.dota2.com/datafeed';
const dataFile = (name) => fileURLToPath(new URL(`../src/data/${name}`, import.meta.url));

async function get(url) {
  for (let attempt = 1; ; attempt++) {
    const res = await fetch(url);
    if (res.ok) return res.json();
    if (attempt === 3) throw new Error(`${url} responded ${res.status}`);
    await new Promise((r) => setTimeout(r, 1000 * attempt));
  }
}

/** Runs `fn` over items with limited concurrency, keeping order. */
async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: limit }, async () => {
      while (next < items.length) {
        const i = next++;
        out[i] = await fn(items[i]);
      }
    }),
  );
  return out;
}

const [heroData, patchList] = await Promise.all([
  get(`${OPENDOTA}/heroes`),
  get(`${VALVE}/patchnoteslist?language=english`),
]);

const heroes = Object.values(heroData)
  .map((h) => ({
    id: h.id,
    key: h.name.replace('npc_dota_hero_', ''),
    name: h.localized_name,
    attr: h.primary_attr,
    attack: h.attack_type,
    roles: h.roles,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

await writeFile(
  dataFile('heroes.generated.ts'),
  `// Generated by scripts/sync-heroes.mjs from ${OPENDOTA}/heroes. Do not edit by hand.
import type { BaseHero } from '../types';

export const BASE_HEROES: readonly BaseHero[] = [
${heroes.map((h) => `  ${JSON.stringify(h)},`).join('\n')}
];
`,
);

const kits = await mapLimit(heroes, 8, async (h) => {
  const data = await get(`${VALVE}/herodata?language=english&hero_id=${h.id}`);
  const abilities = data.result?.data?.heroes?.[0]?.abilities ?? [];
  return [h.key, abilities.map((a) => a.name).filter((n) => n && !/^(generic_hidden|dota_empty_ability)/.test(n))];
});
const missing = kits.filter(([, abilities]) => !abilities.length).map(([key]) => key);
if (missing.length) throw new Error(`No abilities returned for: ${missing.join(', ')}`);

const patch = patchList.patches.at(-1).patch_number;

await writeFile(
  dataFile('hero-abilities.generated.ts'),
  `// Generated by scripts/sync-heroes.mjs from ${VALVE}/herodata. Do not edit by hand.
// Used by tests and scripts to check combos against each hero's current kit; not shipped to the app.

/** Patch the snapshot below was taken on. */
export const ABILITIES_PATCH = ${JSON.stringify(patch)};

export const HERO_ABILITIES: Readonly<Record<string, readonly string[]>> = {
${kits.map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join('\n')}
};
`,
);

console.log(`Wrote ${heroes.length} heroes and their abilities (patch ${patch})`);
