// Pulls the current hero list from OpenDota and regenerates src/data/heroes.generated.ts.
// Run after a new hero is released, then add the hero to src/data/hero-meta.ts
// (the test suite fails until you do, so it can't be forgotten).
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://api.opendota.com/api/constants/heroes';
const out = fileURLToPath(new URL('../src/data/heroes.generated.ts', import.meta.url));

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`OpenDota responded ${res.status}`);
const data = await res.json();

const heroes = Object.values(data)
  .map((h) => ({
    id: h.id,
    key: h.name.replace('npc_dota_hero_', ''),
    name: h.localized_name,
    attr: h.primary_attr,
    attack: h.attack_type,
    roles: h.roles,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const body = heroes.map((h) => `  ${JSON.stringify(h)},`).join('\n');
await writeFile(
  out,
  `// Generated by scripts/sync-heroes.mjs from ${SOURCE}. Do not edit by hand.
import type { BaseHero } from '../types';

export const BASE_HEROES: readonly BaseHero[] = [
${body}
];
`,
);
console.log(`Wrote ${heroes.length} heroes to ${out}`);
