/** "classic" holds up in serious games; "meme" is pub/Turbo shenanigans. */
export type ComboStyle = 'classic' | 'meme';

export interface Combo {
  /** Stable id: saved drafts and share links refer to it. */
  id: string;
  name: string;
  /** Hero keys that make up the combo. */
  heroes: string[];
  how: string;
  style: ComboStyle;
  /**
   * Internal ability names the combo relies on (e.g. "tidehunter_ravage"). Tests check they're in
   * each hero's current kit; the weekly patch check flags the combo when any of them change.
   */
  abilities: string[];
  /** Patch the combo was last checked against, e.g. "7.41f". */
  verifiedPatch: string;
  /** Requirement or caveat worth knowing before trying it, e.g. "Needs Aghanim's Scepter". */
  note?: string;
  /** A famous time it happened, e.g. "TI5: Universe's $6M Echo Slam vs CDEC". */
  moment?: string;
  /** Where the combo or moment is documented. */
  source?: string;
}

/**
 * Hand-curated combos, verified against the patch in each entry's `verifiedPatch`.
 * Bar for inclusion: a specific chain of big abilities with a payoff (classic), or a pub/Turbo
 * trick that makes people laugh (meme). Plain "these heroes are good together" pairings don't count.
 * See "Keeping combos current" in the README for how they're re-checked after patches.
 */
export const COMBOS: readonly Combo[] = [
  // Classic chains: duos
  {
    id: 'ravage-bh',
    name: 'Ravage into Black Hole',
    heroes: ['tidehunter', 'enigma'],
    how: 'Ravage → Black Hole as the stun ends → Midnight Pulse inside the vortex',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'enigma_black_hole', 'enigma_midnight_pulse'],
    verifiedPatch: '7.41f',
    moment: 'TI2: EG\'s Ravage + Black Hole take a map off iG',
    source: 'https://www.gosugamers.net/dota2/features/38100-do-you-remember-the-big-plays-throughout-dota-2-s-history',
  },
  {
    id: 'rp-echo',
    name: 'RP into Echo Slam',
    heroes: ['magnataur', 'earthshaker'],
    how: 'Reverse Polarity → Earthshaker blinks onto the stunned stack → Echo Slam',
    style: 'classic',
    abilities: ['magnataur_reverse_polarity', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'ravage-echo',
    name: 'Ravage into Echo Slam',
    heroes: ['tidehunter', 'earthshaker'],
    how: 'Ravage → Earthshaker blinks into the stunned clump → Echo Slam',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'chrono-ward',
    name: 'Chrono Death Ward',
    heroes: ['faceless_void', 'witch_doctor'],
    how: 'Chronosphere → Witch Doctor drops Death Ward just outside the dome → it shreds the frozen heroes',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'witch_doctor_death_ward'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'chrono-flare',
    name: 'Chrono Mystic Flare',
    heroes: ['faceless_void', 'skywrath_mage'],
    how: 'Chronosphere → Ancient Seal → Mystic Flare from outside the dome onto the frozen pile',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'skywrath_mage_ancient_seal', 'skywrath_mage_mystic_flare'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'chrono-freeze',
    name: 'Frozen in Time',
    heroes: ['faceless_void', 'crystal_maiden'],
    how: 'Chronosphere → CM stands just outside the edge → Freezing Field explosions rain into the dome',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'crystal_maiden_freezing_field'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'bh-macropyre',
    name: 'Black Hole Macropyre',
    heroes: ['enigma', 'jakiro'],
    how: 'Black Hole → Macropyre across the vortex → Ice Path catches anyone who survives',
    style: 'classic',
    abilities: ['enigma_black_hole', 'jakiro_macropyre', 'jakiro_ice_path'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'bh-sonic',
    name: 'Black Hole Sonic Wave',
    heroes: ['enigma', 'queenofpain'],
    how: 'Black Hole → QoP Blinks to the edge → Sonic Wave through the whole vortex',
    style: 'classic',
    abilities: ['enigma_black_hole', 'queenofpain_blink', 'queenofpain_sonic_wave'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'vacuum-rp',
    name: 'Vacuum into RP',
    heroes: ['dark_seer', 'magnataur'],
    how: 'Vacuum stacks them → Reverse Polarity on the clump → 5 heroes stunned in one spot',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'magnataur_reverse_polarity'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'vacuum-echo',
    name: 'Vacuum into Echo Slam',
    heroes: ['dark_seer', 'earthshaker'],
    how: 'Vacuum stacks them on one spot → Earthshaker blinks in → Echo Slam',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'empower-cleave',
    name: 'Empowered Cleave',
    heroes: ['magnataur', 'sven'],
    how: 'Empower Sven → Reverse Polarity → God\'s Strength cleaves the whole stunned pile',
    style: 'classic',
    abilities: ['magnataur_empower', 'magnataur_reverse_polarity', 'sven_gods_strength'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'kinetic-chain',
    name: 'Chain Frost in a Box',
    heroes: ['disruptor', 'lich'],
    how: 'Kinetic Field → Static Storm → Chain Frost ricochets around the cage',
    style: 'classic',
    abilities: ['disruptor_kinetic_field', 'disruptor_static_storm', 'lich_chain_frost'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'arena-macropyre',
    name: 'Arena of Fire',
    heroes: ['mars', 'jakiro'],
    how: 'Arena of Blood → Ice Path → Macropyre down the middle of the arena',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'jakiro_ice_path', 'jakiro_macropyre'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'arena-wukong',
    name: 'Ring of Death',
    heroes: ['mars', 'monkey_king'],
    how: 'Arena of Blood → Wukong\'s Command inside: soldiers stab, the spear wall pushes them back in',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'monkey_king_wukongs_command'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'rp-supernova',
    name: 'Sun Pull',
    heroes: ['magnataur', 'phoenix'],
    how: 'Reverse Polarity → Supernova on the stunned pile → they wake up inside a sun',
    style: 'classic',
    abilities: ['magnataur_reverse_polarity', 'phoenix_supernova'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'song-echo',
    name: 'Siren Echo',
    heroes: ['naga_siren', 'earthshaker'],
    how: 'Song of the Siren → ES walks into the middle → Naga recasts to end Song → Echo Slam',
    style: 'classic',
    abilities: ['naga_siren_song_of_the_siren', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'sun-in-the-colosseum',
    name: 'Sun in the Colosseum',
    heroes: ['mars', 'phoenix'],
    how: 'Arena of Blood → Supernova just outside the wall so they can\'t hit the egg → Sun Ray the trapped pile',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'phoenix_supernova', 'phoenix_sun_ray'],
    verifiedPatch: '7.41f',
    source: 'https://www.hotspawn.com/dota2/guide/the-best-dota-2-hero-combos-to-try-with-your-friends',
  },
  {
    id: 'gladiator-barbecue',
    name: 'Gladiator Barbecue',
    heroes: ['mars', 'snapfire'],
    how: 'Spear of Mars → Arena of Blood → Mortimer Kisses rains into the pit while nobody can walk out',
    style: 'classic',
    abilities: ['mars_spear', 'mars_arena_of_blood', 'snapfire_mortimer_kisses'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/snapfire',
  },
  {
    id: 'fear-cage',
    name: 'Fear Cage',
    heroes: ['mars', 'dark_willow'],
    how: 'Arena of Blood → Terrorize: they flee into the spear wall → Bedlam shreds the panicking pile',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'dark_willow_terrorize', 'dark_willow_bedlam'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/dark-willow',
  },
  {
    id: 'titans-arena',
    name: 'Titan\'s Arena',
    heroes: ['mars', 'elder_titan'],
    how: 'Arena of Blood → Echo Stomp the trapped team → Natural Order strips armor → Earth Splitter',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'elder_titan_echo_stomp', 'elder_titan_natural_order', 'elder_titan_earth_splitter'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/elder-titan',
  },
  {
    id: 'kraken-and-the-ghostship',
    name: 'Kraken & the Ghostship',
    heroes: ['tidehunter', 'kunkka'],
    how: 'Ravage → Torrent under the stunned pile → Ghostship crashes in before anyone stands up',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'kunkka_torrent', 'kunkka_ghostship'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/kunkka',
  },
  {
    id: 'ravage-supernova',
    name: 'Ravage Supernova',
    heroes: ['tidehunter', 'phoenix'],
    how: 'Ravage → Supernova in the middle of the stunned team → they wake up inside a sun',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'phoenix_supernova'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/tidehunter',
  },
  {
    id: 'tentacles-and-golems',
    name: 'Tentacles & Golems',
    heroes: ['tidehunter', 'warlock'],
    how: 'Ravage → Fatal Bonds on the pile → Chaotic Offering lands as the stun ends',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'warlock_fatal_bonds', 'warlock_rain_of_chaos'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/warlock',
  },
  {
    id: 'event-horizon-golems',
    name: 'Event Horizon Golems',
    heroes: ['enigma', 'warlock'],
    how: 'Black Hole → Fatal Bonds the vortex → Chaotic Offering as it ends; bonded damage hits all five',
    style: 'classic',
    abilities: ['enigma_black_hole', 'warlock_fatal_bonds', 'warlock_rain_of_chaos'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/warlock',
  },
  {
    id: 'black-hole-echo',
    name: 'Black Hole Echo',
    heroes: ['enigma', 'earthshaker'],
    how: 'Black Hole sucks them into one point → Earthshaker blinks in → Echo Slam off a perfect stack',
    style: 'classic',
    abilities: ['enigma_black_hole', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    source: 'https://winio.ai/wiki/dota2/heroes/earthshaker',
  },
  {
    id: 'vortex-cataclysm',
    name: 'Vortex Cataclysm',
    heroes: ['enigma', 'invoker'],
    how: 'Black Hole → Chaos Meteor + Deafening Blast into the vortex → double-tap Sun Strike for Cataclysm',
    style: 'classic',
    abilities: ['enigma_black_hole', 'invoker_chaos_meteor', 'invoker_deafening_blast', 'invoker_sun_strike'],
    verifiedPatch: '7.41f',
    note: 'Cataclysm needs Invoker\'s Aghanim\'s Scepter (double-tap Sun Strike).',
    source: 'https://dotacoach.gg/en/heroes/counters/invoker',
  },
  {
    id: 'lasso-delivery',
    name: 'Lasso Delivery',
    heroes: ['enigma', 'batrider'],
    how: 'Flaming Lasso a target (Scepter grabs two) → drag them into Black Hole → Firefly circles the vortex',
    style: 'classic',
    abilities: ['batrider_flaming_lasso', 'enigma_black_hole', 'batrider_firefly'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/enigma',
  },
  {
    id: 'vacuum-black-hole',
    name: 'Vacuum Black Hole',
    heroes: ['enigma', 'dark_seer'],
    how: 'Vacuum stacks them → Black Hole on the clump → Midnight Pulse eats % HP while they spin',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'enigma_black_hole', 'enigma_midnight_pulse'],
    verifiedPatch: '7.41f',
    moment: 'TI2 groups: LightOfHeaven\'s Vacuum into Puppey\'s Black Hole vs TongFu',
    source: 'https://www.gosugamers.net/dota2/features/38100-do-you-remember-the-big-plays-throughout-dota-2-s-history',
  },
  {
    id: 'chrono-cataclysm',
    name: 'Chrono Cataclysm',
    heroes: ['faceless_void', 'invoker'],
    how: 'Chronosphere → Chaos Meteor rolls through → double-tap Sun Strike: Cataclysm on everyone inside',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'invoker_chaos_meteor', 'invoker_sun_strike'],
    verifiedPatch: '7.41f',
    note: 'Cataclysm needs Invoker\'s Aghanim\'s Scepter.',
    source: 'https://www.hotspawn.com/dota2/guide/the-best-dota-2-hero-combos-to-try-with-your-friends',
  },
  {
    id: 'time-shatter',
    name: 'Time Shatter',
    heroes: ['faceless_void', 'ancient_apparition'],
    how: 'Chronosphere → Cold Feet on the frozen heroes → Ice Blast so the shatter executes them as it ends',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'ancient_apparition_cold_feet', 'ancient_apparition_ice_blast'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/faceless-void',
  },
  {
    id: 'chrono-golems',
    name: 'Chrono Golems',
    heroes: ['faceless_void', 'warlock'],
    how: 'Chronosphere → Upheaval from outside the dome → Chaotic Offering + Fatal Bonds as it drops',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'warlock_upheaval', 'warlock_rain_of_chaos', 'warlock_fatal_bonds'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/warlock',
  },
  {
    id: 'monkeys-ignore-time',
    name: 'Monkeys Ignore Time',
    heroes: ['faceless_void', 'monkey_king'],
    how: 'Wukong\'s Command → Chronosphere on the ring: soldiers aren\'t frozen and keep stabbing everyone',
    style: 'classic',
    abilities: ['monkey_king_wukongs_command', 'faceless_void_chronosphere'],
    verifiedPatch: '7.41f',
    note: 'Liquipedia lists Wukong\'s Command soldiers as unaffected by Chronosphere.',
    source: 'https://dotacoach.gg/en/heroes/counters/monkey-king',
  },
  {
    id: 'polarity-meteor',
    name: 'Polarity Meteor',
    heroes: ['magnataur', 'invoker'],
    how: 'Reverse Polarity → Chaos Meteor + Deafening Blast into the stack → Sun Strike the stunned center',
    style: 'classic',
    abilities: ['magnataur_reverse_polarity', 'invoker_chaos_meteor', 'invoker_deafening_blast', 'invoker_sun_strike'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/invoker',
  },
  {
    id: 'vacuum-ring',
    name: 'Vacuum Ring',
    heroes: ['dark_seer', 'monkey_king'],
    how: 'Vacuum → Boundless Strike the clump → Wukong\'s Command around them before they recover',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'monkey_king_boundless_strike', 'monkey_king_wukongs_command'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/monkey-king',
  },
  {
    id: 'kinetic-echo',
    name: 'Kinetic Echo',
    heroes: ['disruptor', 'earthshaker'],
    how: 'Kinetic Field → Static Storm silences the cage → Earthshaker blinks in for Echo Slam',
    style: 'classic',
    abilities: ['disruptor_kinetic_field', 'disruptor_static_storm', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    source: 'https://www.sportskeeda.com/esports/top-5-support-combos-dota-2-patch-7-29c',
  },
  {
    id: 'zombie-cage',
    name: 'Zombie Cage',
    heroes: ['disruptor', 'undying'],
    how: 'Kinetic Field → Tombstone inside the ring → Flesh Golem; Glimpse anyone who slips out',
    style: 'classic',
    abilities: ['disruptor_kinetic_field', 'undying_tombstone', 'undying_flesh_golem', 'disruptor_glimpse'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/disruptor',
  },
  {
    id: 'coil-slam',
    name: 'Coil Slam',
    heroes: ['puck', 'earthshaker'],
    how: 'Dream Coil leashes the team → Echo Slam → anyone who snaps the coil eats a second stun',
    style: 'classic',
    abilities: ['puck_dream_coil', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/earthshaker',
  },
  {
    id: 'coil-and-shatter',
    name: 'Coil & Shatter',
    heroes: ['puck', 'ancient_apparition'],
    how: 'Dream Coil → Cold Feet → Ice Blast: stay and freeze, or snap the coil and get stunned',
    style: 'classic',
    abilities: ['puck_dream_coil', 'ancient_apparition_cold_feet', 'ancient_apparition_ice_blast'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/puck',
  },
  {
    id: 'overgrown-sun',
    name: 'Overgrown Sun',
    heroes: ['treant', 'phoenix'],
    how: 'Overgrowth roots the team → Supernova on top of them → they can\'t walk away or attack the egg',
    style: 'classic',
    abilities: ['treant_overgrowth', 'phoenix_supernova'],
    verifiedPatch: '7.41f',
    source: 'https://hawk.live/posts/best-hero-combos-in-dota-2',
  },
  {
    id: 'x-marks-the-requiem',
    name: 'X Marks the Requiem',
    heroes: ['kunkka', 'nevermore'],
    how: 'X Marks the Spot → SF walks onto the X → the enemy snaps back into a point-blank Requiem',
    style: 'classic',
    abilities: ['kunkka_x_marks_the_spot', 'nevermore_requiem'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/kunkka',
  },
  {
    id: 'torrent-flare',
    name: 'Torrent Flare',
    heroes: ['kunkka', 'skywrath_mage'],
    how: 'X Marks → Torrent on the return spot → Ancient Seal → Mystic Flare on a target that can\'t move',
    style: 'classic',
    abilities: ['kunkka_x_marks_the_spot', 'kunkka_torrent', 'skywrath_mage_ancient_seal', 'skywrath_mage_mystic_flare'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/kunkka',
  },
  {
    id: 'bonded-epicenter',
    name: 'Bonded Epicenter',
    heroes: ['sand_king', 'warlock'],
    how: 'Fatal Bonds on the team → Sand King blinks in with Epicenter → every pulse echoes through the bond',
    style: 'classic',
    abilities: ['warlock_fatal_bonds', 'sandking_epicenter'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/sand-king',
  },
  {
    id: 'double-finger',
    name: 'Double Finger',
    heroes: ['grimstroke', 'lion'],
    how: 'Soulbind two heroes → Hex → Finger of Death; both spells copy onto the bound partner',
    style: 'classic',
    abilities: ['grimstroke_soul_chain', 'lion_voodoo', 'lion_finger_of_death'],
    verifiedPatch: '7.41f',
    source: 'https://www.sportskeeda.com/esports/top-5-support-combos-dota-2-patch-7-29c',
  },
  {
    id: 'two-dooms',
    name: 'Two Dooms',
    heroes: ['grimstroke', 'doom_bringer'],
    how: 'Soulbind their two cores → Doom one of them → the curse copies onto the bound partner',
    style: 'classic',
    abilities: ['grimstroke_soul_chain', 'doom_bringer_doom'],
    verifiedPatch: '7.41f',
    source: 'https://hawk.live/posts/best-hero-combos-in-dota-2',
  },
  {
    id: 'arrow-on-exit',
    name: 'Arrow on Exit',
    heroes: ['shadow_demon', 'mirana'],
    how: 'Disruption → fire Sacred Arrow so it arrives as they reappear → max-range stun',
    style: 'classic',
    abilities: ['shadow_demon_disruption', 'mirana_arrow'],
    verifiedPatch: '7.41f',
    source: 'https://www.hotspawn.com/dota2/guide/the-best-dota-2-hero-combos-to-try-with-your-friends',
  },
  {
    id: 'duel-flare',
    name: 'Duel Flare',
    heroes: ['legion_commander', 'skywrath_mage'],
    how: 'Duel → Ancient Seal → Mystic Flare: all the flare damage lands on one dueled hero',
    style: 'classic',
    abilities: ['legion_commander_duel', 'skywrath_mage_ancient_seal', 'skywrath_mage_mystic_flare'],
    verifiedPatch: '7.41f',
    source: 'https://www.hotspawn.com/dota2/guide/the-best-dota-2-hero-combos-to-try-with-your-friends',
  },
  {
    id: 'cog-freezer',
    name: 'Cog Freezer',
    heroes: ['rattletrap', 'ancient_apparition'],
    how: 'Hookshot → Power Cogs trap the target → Cold Feet → Ice Blast: no heal, no escape',
    style: 'classic',
    abilities: ['rattletrap_hookshot', 'rattletrap_power_cogs', 'ancient_apparition_cold_feet', 'ancient_apparition_ice_blast'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/clockwerk',
  },
  {
    id: 'called-to-the-frost',
    name: 'Called to the Frost',
    heroes: ['axe', 'lich'],
    how: 'Berserker\'s Call clumps them on Axe → Chain Frost bounces endlessly through the pile',
    style: 'classic',
    abilities: ['axe_berserkers_call', 'lich_chain_frost'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/lich',
  },

  {
    id: 'six-million-dollar-echo',
    name: 'Six Million Dollar Echo',
    heroes: ['ancient_apparition', 'earthshaker'],
    how: 'Ice Blast the clumped team → Earthshaker blinks in → Echo Slam drops them under the shatter line',
    style: 'classic',
    abilities: ['ancient_apparition_ice_blast', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    moment: 'TI5 GF G4: ppd\'s Ice Blast + UNiVeRsE\'s $6M Echo Slam vs CDEC',
    source: 'https://kotaku.com/the-dota-2-play-that-won-6-million-1723390801',
  },
  {
    id: 'million-dollar-dream-coil',
    name: 'Million Dollar Dream Coil',
    heroes: ['puck', 'furion'],
    how: 'Prophet splits their base → defenders TP home → Dream Coil leashes them and cancels every TP',
    style: 'classic',
    abilities: ['puck_dream_coil', 'furion_teleportation'],
    verifiedPatch: '7.41f',
    note: 'Dream Coil no longer stuns on cast, but its leash still cancels teleports.',
    moment: 'TI3 GF G5: s4\'s Dream Coil cancels Na\'Vi\'s TPs vs Bulldog\'s push',
    source: 'https://www.oneesports.gg/dota2/s4-left-alliance-dota-2-roster',
  },
  {
    id: 'skewer-into-chrono',
    name: 'Skewer into Chrono',
    heroes: ['magnataur', 'faceless_void'],
    how: 'Empower Void → Skewer their core into your team → Chronosphere → Void cleaves the frozen pile',
    style: 'classic',
    abilities: ['magnataur_empower', 'magnataur_skewer', 'faceless_void_chronosphere'],
    verifiedPatch: '7.41f',
    note: 'Skewer before the Chrono lands: Chronosphere freezes Magnus too.',
    moment: 'TI12 GF G2: Collapse\'s Skewer + Yatoro\'s Chrono rampage vs GG',
    source: 'https://www.gosugamers.net/dota2/news/69851-team-spirit-are-the-ti12-champions',
  },
  {
    id: 'black-hole-requiem',
    name: 'Black Hole Requiem',
    heroes: ['enigma', 'nevermore'],
    how: 'Black Hole the team → Shadow Fiend walks into the vortex → Requiem of Souls hits all five',
    style: 'classic',
    abilities: ['enigma_black_hole', 'nevermore_requiem'],
    verifiedPatch: '7.41f',
    moment: 'Riyadh Masters 2023: MieRo\'s Black Hole + kiyotaka\'s Requiem vs GG',
    source: 'https://sportskeeda.com/esports/best-group-stage-highlights-dota-2-riyadh-masters-2023',
  },
  {
    id: 'ravage-and-poof',
    name: 'Ravage and Poof',
    heroes: ['tidehunter', 'meepo'],
    how: 'Ravage the whole team → every Meepo Poofs onto the stun → Earthbind chain before they stand up',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'meepo_poof', 'meepo_earthbind'],
    verifiedPatch: '7.41f',
    moment: 'TI9: zai\'s 5-man Ravage + MidOne\'s Meepo flip 25k gold vs Mineski',
    source: 'https://www.oneesports.gg/dota2/most-memorable-dota-2-games-all-time/',
  },
  {
    id: 'vacuum-ice-path',
    name: 'Vacuum Ice Path',
    heroes: ['dark_seer', 'jakiro'],
    how: 'Vacuum stacks them in a line → one Ice Path stuns the whole clump → Macropyre down the middle',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'jakiro_ice_path', 'jakiro_macropyre'],
    verifiedPatch: '7.41f',
    moment: 'TI3 groups: Funn1k\'s 4-man Vacuum into Puppey\'s Ice Path vs mouz',
    source: 'https://www.gosugamers.net/dota2/features/38100-do-you-remember-the-big-plays-throughout-dota-2-s-history',
  },

  // Classic chains: trios
  {
    id: 'chrono-massacre',
    name: 'Time Stop Massacre',
    heroes: ['faceless_void', 'witch_doctor', 'skywrath_mage'],
    how: 'Chronosphere → Death Ward just outside the edge → Ancient Seal + Mystic Flare on the frozen',
    style: 'classic',
    abilities: ['faceless_void_chronosphere', 'witch_doctor_death_ward', 'skywrath_mage_mystic_flare'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'hell-arena',
    name: 'Hell Arena',
    heroes: ['mars', 'lich', 'jakiro'],
    how: 'Arena of Blood → Chain Frost bouncing inside → Macropyre down the middle',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'lich_chain_frost', 'jakiro_macropyre'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'mega-wombo',
    name: 'The Mega Wombo',
    heroes: ['tidehunter', 'enigma', 'queenofpain'],
    how: 'Ravage → Black Hole as the stun ends → Sonic Wave through the vortex',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'enigma_black_hole', 'queenofpain_sonic_wave'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'gravity-well',
    name: 'Gravity Well',
    heroes: ['dark_seer', 'magnataur', 'earthshaker'],
    how: 'Vacuum → Reverse Polarity → Echo Slam on a perfect stack',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'magnataur_reverse_polarity', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
  },
  {
    id: 'colosseum-inferno',
    name: 'Colosseum Inferno',
    heroes: ['mars', 'phoenix', 'snapfire'],
    how: 'Arena of Blood → Supernova outside the wall → Mortimer Kisses into the trapped pile',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'phoenix_supernova', 'snapfire_mortimer_kisses'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/mars',
  },
  {
    id: 'kraken-boat-and-kisses',
    name: 'Kraken, Boat & Kisses',
    heroes: ['tidehunter', 'kunkka', 'snapfire'],
    how: 'Ravage → Torrent + Ghostship → Mortimer Kisses on everyone still stunned',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'kunkka_torrent', 'kunkka_ghostship', 'snapfire_mortimer_kisses'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/kunkka',
  },
  {
    id: 'vacuum-golem-hole',
    name: 'Vacuum Golem Hole',
    heroes: ['dark_seer', 'enigma', 'warlock'],
    how: 'Vacuum → Black Hole → Fatal Bonds the vortex → Chaotic Offering as it ends',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'enigma_black_hole', 'warlock_fatal_bonds', 'warlock_rain_of_chaos'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/enigma',
  },
  {
    id: 'coil-cage-echo',
    name: 'Coil Cage Echo',
    heroes: ['puck', 'disruptor', 'earthshaker'],
    how: 'Dream Coil → Kinetic Field + Static Storm → Echo Slam on a silenced, caged team',
    style: 'classic',
    abilities: ['puck_dream_coil', 'disruptor_kinetic_field', 'disruptor_static_storm', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/disruptor',
  },
  {
    id: 'polarity-echo-strike',
    name: 'Polarity Echo Strike',
    heroes: ['magnataur', 'invoker', 'earthshaker'],
    how: 'Reverse Polarity → Echo Slam the stack → Chaos Meteor + Cataclysm finish the rest',
    style: 'classic',
    abilities: ['magnataur_reverse_polarity', 'earthshaker_echo_slam', 'invoker_chaos_meteor', 'invoker_sun_strike'],
    verifiedPatch: '7.41f',
    note: 'Cataclysm needs Invoker\'s Aghanim\'s Scepter.',
    source: 'https://dotacoach.gg/en/heroes/counters/earthshaker',
  },
  {
    id: 'ravage-sun-golems',
    name: 'Ravage Sun Golems',
    heroes: ['tidehunter', 'phoenix', 'warlock'],
    how: 'Ravage → Supernova in the pile → Upheaval + Chaotic Offering keep them in the sun',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'phoenix_supernova', 'warlock_upheaval', 'warlock_rain_of_chaos'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/phoenix',
  },
  {
    id: 'arena-splitter',
    name: 'Arena Splitter',
    heroes: ['mars', 'elder_titan', 'disruptor'],
    how: 'Arena of Blood → Kinetic Field + Static Storm → Echo Stomp → Earth Splitter',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'disruptor_kinetic_field', 'disruptor_static_storm', 'elder_titan_echo_stomp', 'elder_titan_earth_splitter'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/elder-titan',
  },
  {
    id: 'x-marks-the-echo',
    name: 'X Marks the Echo',
    heroes: ['kunkka', 'disruptor', 'earthshaker'],
    how: 'X Marks → Torrent → Static Storm on the return spot → Ghostship → Echo Slam',
    style: 'classic',
    abilities: ['kunkka_x_marks_the_spot', 'kunkka_torrent', 'disruptor_static_storm', 'kunkka_ghostship', 'earthshaker_echo_slam'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/kunkka',
  },

  // Classic chains: 4–5 heroes
  {
    id: 'death-ball',
    name: 'Death Ball',
    heroes: ['tidehunter', 'enigma', 'disruptor', 'gyrocopter'],
    how: 'Ravage → Black Hole as it ends → Static Storm on the vortex → Call Down + Flak Cannon',
    style: 'classic',
    abilities: ['tidehunter_ravage', 'enigma_black_hole', 'disruptor_static_storm', 'gyrocopter_call_down', 'gyrocopter_flak_cannon'],
    verifiedPatch: '7.41f',
    source: 'https://www.ludo.guide/guide/dota-2/heroes-abilities/heroes/hero-synergies/push-siege-combos',
  },
  {
    id: 'colosseum-of-doom',
    name: 'Colosseum of Doom',
    heroes: ['mars', 'phoenix', 'snapfire', 'warlock'],
    how: 'Arena of Blood → Supernova → Mortimer Kisses → Fatal Bonds + Chaotic Offering',
    style: 'classic',
    abilities: ['mars_arena_of_blood', 'phoenix_supernova', 'snapfire_mortimer_kisses', 'warlock_fatal_bonds', 'warlock_rain_of_chaos'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/mars',
  },
  {
    id: 'all-in-wombo',
    name: 'All-In Wombo',
    heroes: ['dark_seer', 'enigma', 'magnataur', 'earthshaker', 'invoker'],
    how: 'Vacuum → Black Hole → Echo Slam → Cataclysm → Reverse Polarity whoever is left standing',
    style: 'classic',
    abilities: ['dark_seer_vacuum', 'enigma_black_hole', 'earthshaker_echo_slam', 'invoker_sun_strike', 'magnataur_reverse_polarity'],
    verifiedPatch: '7.41f',
    note: 'Cataclysm needs Invoker\'s Aghanim\'s Scepter.',
    source: 'https://dotacoach.gg/en/heroes/counters/enigma',
  },

  {
    id: 'four-stun-chain',
    name: 'Four-Stun Chain',
    heroes: ['visage', 'dark_seer', 'slardar', 'nyx_assassin'],
    how: 'Familiars Stone Form → Vacuum groups them → Slithereen Crush → Impale: stunned for days',
    style: 'classic',
    abilities: ['visage_summon_familiars', 'dark_seer_vacuum', 'slardar_slithereen_crush', 'nyx_assassin_impale'],
    verifiedPatch: '7.41f',
    moment: 'TI3: Orange chain Birds, Vacuum, 4-man Crush + Impale vs DK',
    source: 'https://www.gosugamers.net/dota2/features/38100-do-you-remember-the-big-plays-throughout-dota-2-s-history',
  },

  // Memes: duos
  {
    id: 'pudge-delivery',
    name: 'Pudge Delivery',
    heroes: ['snapfire', 'pudge'],
    how: 'Gobble Up Pudge → Spit Out into their backline (stun) → Dismember the support while Rot ticks',
    style: 'meme',
    abilities: ['snapfire_gobble_up', 'snapfire_spit_creep', 'pudge_dismember', 'pudge_rot'],
    verifiedPatch: '7.41f',
    note: 'Gobble Up needs Snapfire\'s Aghanim\'s Scepter.',
    source: 'https://www.youtube.com/watch?v=wKb7LwQF4I0',
  },
  {
    id: 'flying-butcher',
    name: 'Flying Butcher',
    heroes: ['tiny', 'pudge'],
    how: 'Tiny Tosses Pudge onto their carry → he lands unharmed with Rot on → instant Dismember',
    style: 'meme',
    abilities: ['tiny_toss', 'pudge_rot', 'pudge_dismember'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/pudge',
  },
  {
    id: 'snowball-surprise',
    name: 'Snowball Surprise',
    heroes: ['tusk', 'life_stealer'],
    how: 'Lifestealer Infests Tusk → Snowball → Walrus PUNCH! → Lifestealer bursts out on the victim',
    style: 'meme',
    abilities: ['life_stealer_infest', 'tusk_snowball', 'tusk_walrus_punch'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/tusk',
  },
  {
    id: 'infest-express',
    name: 'Infest Express',
    heroes: ['spirit_breaker', 'life_stealer'],
    how: 'Lifestealer Infests Bara → Charge of Darkness across the map → Nether Strike → pop out',
    style: 'meme',
    abilities: ['life_stealer_infest', 'spirit_breaker_charge_of_darkness', 'spirit_breaker_nether_strike', 'life_stealer_open_wounds'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/lifestealer',
  },
  {
    id: 'rebound-bomb',
    name: 'Rebound Bomb',
    heroes: ['marci', 'life_stealer'],
    how: 'Lifestealer Infests Marci → Rebound onto their support → pop out and both start swinging',
    style: 'meme',
    abilities: ['life_stealer_infest', 'marci_companion_run', 'marci_unleash'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/marci',
  },
  {
    id: 'snowball-duel',
    name: 'Snowball Duel',
    heroes: ['tusk', 'legion_commander'],
    how: 'LC hops into the Snowball → it rolls over their carry → she lands on top → Duel',
    style: 'meme',
    abilities: ['tusk_snowball', 'legion_commander_duel'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/tusk',
  },
  {
    id: 'double-dismember',
    name: 'Double Dismember',
    heroes: ['grimstroke', 'pudge'],
    how: 'Soulbind two enemies → Pudge Dismembers one → the bound partner gets eaten too',
    style: 'meme',
    abilities: ['grimstroke_soul_chain', 'pudge_dismember'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/pudge',
  },
  {
    id: 'double-x',
    name: 'Double X',
    heroes: ['grimstroke', 'kunkka'],
    how: 'Soulbind → X Marks the Spot copies onto both → Torrent the return spot → Ghostship',
    style: 'meme',
    abilities: ['grimstroke_soul_chain', 'kunkka_x_marks_the_spot', 'kunkka_torrent', 'kunkka_ghostship'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/grimstroke',
  },
  {
    id: 'double-concoction',
    name: 'Double Concoction',
    heroes: ['grimstroke', 'alchemist'],
    how: 'Soulbind → Alchemist throws Unstable Concoction at one → a second one flies at the partner',
    style: 'meme',
    abilities: ['grimstroke_soul_chain', 'alchemist_unstable_concoction'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/grimstroke',
  },
  {
    id: 'hook-into-the-minefield',
    name: 'Hook into the Minefield',
    heroes: ['techies', 'pudge'],
    how: 'Plant Proximity Mines → Meat Hook a hero onto them → Dismember → Sticky Bomb + Blast Off!',
    style: 'meme',
    abilities: ['techies_land_mines', 'pudge_meat_hook', 'pudge_dismember', 'techies_sticky_bomb', 'techies_suicide'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'toss-into-the-minefield',
    name: 'Toss into the Minefield',
    heroes: ['techies', 'tiny'],
    how: 'Plant Proximity Mines → Tiny Tosses an enemy into the field → Blast Off! on top of them',
    style: 'meme',
    abilities: ['techies_land_mines', 'tiny_toss', 'techies_suicide'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'lasso-minesweeper',
    name: 'Lasso Minesweeper',
    heroes: ['techies', 'batrider'],
    how: 'Flaming Lasso a hero → drag them through Proximity Mines → Sticky Bomb + Blast Off! finish',
    style: 'meme',
    abilities: ['batrider_flaming_lasso', 'techies_land_mines', 'techies_sticky_bomb', 'techies_suicide'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'swap-onto-the-mines',
    name: 'Swap onto the Mines',
    heroes: ['techies', 'vengefulspirit'],
    how: 'Venge stands on the Proximity Mines → Nether Swap an enemy onto them → Magic Missile → Blast Off!',
    style: 'meme',
    abilities: ['techies_land_mines', 'vengefulspirit_nether_swap', 'vengefulspirit_magic_missile', 'techies_suicide'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'call-and-kaboom',
    name: 'Call & Kaboom',
    heroes: ['techies', 'axe'],
    how: 'Axe blinks onto Techies\' mines → Berserker\'s Call → Blast Off! + Sticky Bomb → Culling Blade',
    style: 'meme',
    abilities: ['axe_berserkers_call', 'techies_land_mines', 'techies_suicide', 'techies_sticky_bomb', 'axe_culling_blade'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/axe',
  },
  {
    id: 'arena-minefield',
    name: 'Arena Minefield',
    heroes: ['techies', 'mars'],
    how: 'Arena of Blood → Techies Blast Off! into the pit → triple Proximity Mines under them',
    style: 'meme',
    abilities: ['mars_arena_of_blood', 'techies_suicide', 'techies_land_mines'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'chaos-clone-army',
    name: 'Chaos Clone Army',
    heroes: ['shadow_demon', 'chaos_knight'],
    how: 'Phantasm → Disruption on Chaos Knight → two extra bonus-damage CKs join the crit party',
    style: 'meme',
    abilities: ['chaos_knight_phantasm', 'shadow_demon_disruption', 'chaos_knight_chaos_strike'],
    verifiedPatch: '7.41f',
    note: 'dotacoach also mentions CK\'s old \'Reins of Chaos\' innate; that is gone (innate is now Fundamental Forging), the Disruption part still works.',
    source: 'https://dotacoach.gg/en/heroes/counters/shadow-demon',
  },
  {
    id: 'back-in-the-bubble',
    name: 'Back in the Bubble',
    heroes: ['marci', 'faceless_void'],
    how: 'Chronosphere → Marci grabs anyone who got away → Dispose throws them into the dome to freeze',
    style: 'meme',
    abilities: ['faceless_void_chronosphere', 'marci_grapple'],
    verifiedPatch: '7.41f',
    note: 'Throwing an enemy in works (units entering Chrono get frozen). Pulling an ally OUT with Dispose no longer works per Liquipedia.',
    source: 'https://www.cybersport.ru/dota-2/articles/chto-nuzhno-znat-o-marci-pered-pervoi-igroi-letaem-po-karte-i-spasaem-soyuznikov-iz-black-hole',
  },
  {
    id: 'swap-out-of-the-chrono',
    name: 'Swap Out of the Chrono',
    heroes: ['vengefulspirit', 'faceless_void'],
    how: 'Void Chronos his own team → Venge Nether Swaps the ally out and freezes herself instead',
    style: 'meme',
    abilities: ['faceless_void_chronosphere', 'vengefulspirit_nether_swap'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/vengeful-spirit',
  },
  {
    id: 'relocate-rp',
    name: 'Relocate RP',
    heroes: ['wisp', 'magnataur'],
    how: 'Tether Magnus → Relocate behind their team → Reverse Polarity → Skewer them home → Relocate back',
    style: 'meme',
    abilities: ['wisp_tether', 'wisp_relocate', 'magnataur_reverse_polarity', 'magnataur_skewer'],
    verifiedPatch: '7.41f',
    note: 'Source is Dota WTF\'s \'Ultra Combo / Magnus IO\'; Tether, Relocate, RP and Skewer all still exist in 7.41f.',
    source: 'https://www.youtube.com/watch?v=K_J2Dba9PHs',
  },
  {
    id: 'horse-and-carriage',
    name: 'Horse & Carriage',
    heroes: ['centaur', 'medusa'],
    how: 'Work Horse → Hitch A Ride Medusa → Stampede into the fight while she Split Shots, untargetable',
    style: 'meme',
    abilities: ['centaur_work_horse', 'centaur_stampede', 'medusa_split_shot'],
    verifiedPatch: '7.41f',
    note: 'Needs Centaur\'s Aghanim\'s Scepter (Work Horse). Hitched ally can attack and cast but can\'t be targeted.',
    source: 'https://dotacoach.gg/en/heroes/counters/centaur-warrunner',
  },

  {
    id: 'zoomies-freezing-field',
    name: 'Zoomies Freezing Field',
    heroes: ['lycan', 'crystal_maiden'],
    how: 'Lycan Wolf Bites CM → Shapeshift speed, can\'t be slowed → BKB → she sprints through their team mid Freezing Field',
    style: 'meme',
    abilities: ['lycan_wolf_bite', 'lycan_shapeshift', 'crystal_maiden_freezing_field'],
    verifiedPatch: '7.41f',
    note: 'Needs Lycan\'s and CM\'s Aghanim\'s Scepters. BKB matters: moving Freezing Field can still be interrupted.',
  },

  // Memes: 3+ heroes
  {
    id: 'enemy-relocation-service',
    name: 'Enemy Relocation Service',
    heroes: ['magnataur', 'tusk', 'tiny'],
    how: 'Skewer their carry toward your team → Walrus Kick sends them flying further → Tiny Tosses them under your tower',
    style: 'meme',
    abilities: ['magnataur_skewer', 'tusk_walrus_kick', 'tiny_toss'],
    verifiedPatch: '7.41f',
    note: 'Walrus Kick needs Tusk\'s Aghanim\'s Scepter.',
  },
  {
    id: 'double-double',
    name: 'Double Double',
    heroes: ['grimstroke', 'lion', 'lina'],
    how: 'Soulbind → Finger of Death + Laguna Blade each copy over: four ults of burst on two heroes',
    style: 'meme',
    abilities: ['grimstroke_soul_chain', 'lion_finger_of_death', 'lina_laguna_blade'],
    verifiedPatch: '7.41f',
    note: 'Liquipedia marks Laguna Blade and Finger of Death as reflectable, which is what Soulbind copies.',
    source: 'https://dotacoach.gg/en/heroes/counters/grimstroke',
  },
  {
    id: 'soulbind-photocopier',
    name: 'Soulbind Photocopier',
    heroes: ['grimstroke', 'lion', 'doom_bringer', 'shadow_shaman'],
    how: 'Soulbind → Hex, Shackles, Finger of Death and Doom all get copied onto the bound partner',
    style: 'meme',
    abilities: ['grimstroke_soul_chain', 'lion_voodoo', 'shadow_shaman_shackles', 'lion_finger_of_death', 'doom_bringer_doom'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/grimstroke',
  },
  {
    id: 'minefield-delivery-service',
    name: 'Minefield Delivery Service',
    heroes: ['techies', 'pudge', 'batrider', 'vengefulspirit', 'tiny'],
    how: 'Techies mines one spot → Hook, Lasso, Swap and Toss drag enemies onto it → Blast Off!',
    style: 'meme',
    abilities: ['techies_land_mines', 'pudge_meat_hook', 'batrider_flaming_lasso', 'vengefulspirit_nether_swap', 'tiny_toss', 'techies_suicide'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/techies',
  },
  {
    id: 'huskar-cant-die',
    name: 'Huskar Can\'t Die',
    heroes: ['huskar', 'dazzle', 'oracle', 'omniknight', 'abaddon'],
    how: 'Huskar Life Breaks in at 1 HP → Shallow Grave → False Promise → Guardian Angel → Aphotic Shield',
    style: 'meme',
    abilities: ['huskar_life_break', 'huskar_berserkers_blood', 'dazzle_shallow_grave', 'oracle_false_promise', 'omniknight_guardian_angel', 'abaddon_aphotic_shield'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/huskar',
  },
  {
    id: 'global-ult-bombardment',
    name: 'Global Ult Bombardment',
    heroes: ['zuus', 'spectre', 'silencer', 'ancient_apparition', 'furion'],
    how: 'Global Silence → Haunt → Ice Blast → Thundergod\'s Wrath → Wrath of Nature; hit them anywhere',
    style: 'meme',
    abilities: ['silencer_global_silence', 'spectre_haunt', 'ancient_apparition_ice_blast', 'zuus_thundergods_wrath', 'furion_wrath_of_nature'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/zeus',
  },
  {
    id: 'nowhere-is-safe',
    name: 'Nowhere Is Safe',
    heroes: ['spectre', 'zuus', 'furion'],
    how: 'Haunt the whole team → Thundergod\'s Wrath → Wrath of Nature: every hero takes three ults at once',
    style: 'meme',
    abilities: ['spectre_haunt', 'zuus_thundergods_wrath', 'furion_wrath_of_nature'],
    verifiedPatch: '7.41f',
    source: 'https://dotacoach.gg/en/heroes/counters/zeus',
  },
];

export const getCombo = (id: string | undefined): Combo | undefined => COMBOS.find((c) => c.id === id);
